name: Continuous integration

on: [push]

jobs:
  test:
    name: Unit and integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Run tests
        run: poetry run pytest

  check:
    name: Lint and type checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Format checks
        run: poetry run black --check
      - name: Lint checks
        run: poetry run pylama
      - name: Type checks
        run: poetry run mypy
